### ISSUE TITLE
Add more information about "github-token" to the documentation

### ISSUE THREAD

**Issue by klein0r** [ioBroker/testing-action-deploy#1]
I've switched to GitHub Action from TravisCI.

Which permissions are required by this action? https://github.com/settings/tokens/new

Please update the documentation

**Comment by AlCalzone** [comment]
You don't need to create it, it exists by default: https://docs.github.com/en/actions/security-guides/automatic-token-authentication.

**Comment by klein0r** [comment]
Okay that was ... easy 😄 Thanks a lot!
