### ISSUE TITLE
Feature: Add `@` to usernames in release text

### ISSUE THREAD

**Issue by klein0r** [ioBroker/testing-action-deploy#11]
e.g. replace `- (klein0r)` with `- (@klein0r)` to enable the "contributors" feature in releases:

<img width="814" alt="Screenshot 2024-03-13 at 09 16 22" src="https://github.com/ioBroker/testing-action-deploy/assets/1959049/8bf3b2e4-2c11-463c-82b9-98ce2981e598">

**Comment by AlCalzone** [comment]
What about doing it in the changelog when writing it?
