### ISSUE TITLE
Warning: The set-output command is deprecated

### ISSUE THREAD

**Issue by HGlab01** [ioBroker/testing-action-deploy#5]
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

https://github.com/ioBroker/testing-action-deploy/blob/cd582b4bca2336ab15bd2662599501cafeaa7fa1/action.yml#L72
https://github.com/ioBroker/testing-action-deploy/blob/cd582b4bca2336ab15bd2662599501cafeaa7fa1/action.yml#L77

Example
https://github.com/HGlab01/ioBroker.fuelpricemonitor/actions/runs/4097249275/jobs/7065518315#step:2:229

**Comment by AlCalzone** [comment]
Does this still happen with the latest version I released yesterday?

**Comment by AlCalzone** [comment]
Ok stupid question, I should have read...

**Comment by HGlab01** [comment]
I guess you saw, it is a different issue...

**Comment by AlCalzone** [comment]
Fixed in 1.1.6
